config/routes.rb
IdpEmulator::Application.routes.draw do
  resources :account_credentials

  match '/saml/signon' => 'saml#signon', :via => :get
  match '/saml/new' => 'saml#new', :via => :get
  match '/saml/echo_name_id' => 'saml#echo_name_id', :via => :post
  match '/saml/login' => 'saml#login', :via => :post
  match '/saml/show' => 'saml#show', :via => :get
  match '/saml/keep_alive' => 'saml#keep_alive', :via => :get
  match '/saml/logout' => 'saml#logout', :via => :get
  match '/saml/finish' => 'saml#finish', :via => :get
  match '/saml/slo' => 'saml#slo', :via => :get
  match '/saml/request_slo' => 'saml#request_slo', :via => :get

end

app/models/account_credential.rb
class AccountCredential < ActiveRecord::Base

  validates :employee_id, :employer_id, :presence => true

  def self.instance
    AccountCredential.first || AccountCredential.new(:employee_id => 'TestEE', :employer_id => 'CH-DEV')
  end
end

app/controllers/account_credentials_controller.rb
class AccountCredentialsController < ApplicationController
  # GET /account_credentials
  # GET /account_credentials.xml
  def index
    @account_credentials = AccountCredential.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @account_credentials }
    end
  end

  # GET /account_credentials/1
  # GET /account_credentials/1.xml
  def show
    @account_credential = AccountCredential.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account_credential }
    end
  end

  # GET /account_credentials/new
  # GET /account_credentials/new.xml
  def new
    @account_credential = AccountCredential.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account_credential }
    end
  end

  # GET /account_credentials/1/edit
  def edit
    @account_credential = AccountCredential.find(params[:id])
  end

  # POST /account_credentials
  # POST /account_credentials.xml
  def create
    @account_credential = AccountCredential.new(params[:account_credential])

    respond_to do |format|
      if @account_credential.save
        format.html { redirect_to(@account_credential, :notice => 'Account credential was successfully created.') }
        format.xml  { render :xml => @account_credential, :status => :created, :location => @account_credential }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account_credential.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /account_credentials/1
  # PUT /account_credentials/1.xml
  def update
    @account_credential = AccountCredential.find(params[:id])

    respond_to do |format|
      if @account_credential.update_attributes(params[:account_credential])
        format.html { redirect_to(@account_credential, :notice => 'Account credential was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account_credential.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /account_credentials/1
  # DELETE /account_credentials/1.xml
  def destroy
    @account_credential = AccountCredential.find(params[:id])
    @account_credential.destroy

    respond_to do |format|
      format.html { redirect_to(account_credentials_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/account_credentials_helper.rb
module AccountCredentialsHelper
end

app/views/account_credentials/_form.html.erb
<%= form_for(@account_credential) do |f| %>
  <% if @account_credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_credential.errors.count, "error") %> prohibited this account_credential from being saved:</h2>

      <ul>
      <% @account_credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.text_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :employer_id %><br />
    <%= f.text_field :employer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_credentials/edit.html.erb
<h1>Editing account_credential</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_credential %> |
<%= link_to 'Back', account_credentials_path %>

app/views/account_credentials/index.html.erb
<h1>Listing account_credentials</h1>

<table>
  <tr>
    <th>Employee</th>
    <th>Employer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @account_credentials.each do |account_credential| %>
  <tr>
    <td><%= account_credential.employee_id %></td>
    <td><%= account_credential.employer_id %></td>
    <td><%= link_to 'Show', account_credential %></td>
    <td><%= link_to 'Edit', edit_account_credential_path(account_credential) %></td>
    <td><%= link_to 'Destroy', account_credential, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account credential', new_account_credential_path %>

app/views/account_credentials/new.html.erb
<h1>New account_credential</h1>

<%= render 'form' %>

<%= link_to 'Back', account_credentials_path %>

app/views/account_credentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @account_credential.employee_id %>
</p>

<p>
  <b>Employer:</b>
  <%= @account_credential.employer_id %>
</p>


<%= link_to 'Edit', edit_account_credential_path(@account_credential) %> |
<%= link_to 'Back', account_credentials_path %>