config/routes.rb
IdpEmulator::Application.routes.draw do
  resources :account_credentials

  match '/saml/signon' => 'saml#signon', :via => :get
  match '/saml/new' => 'saml#new', :via => :get
  match '/saml/echo_name_id' => 'saml#echo_name_id', :via => :post
  match '/saml/login' => 'saml#login', :via => :post
  match '/saml/show' => 'saml#show', :via => :get
  match '/saml/keep_alive' => 'saml#keep_alive', :via => :get
  match '/saml/logout' => 'saml#logout', :via => :get
  match '/saml/finish' => 'saml#finish', :via => :get
  match '/saml/slo' => 'saml#slo', :via => :get
  match '/saml/request_slo' => 'saml#request_slo', :via => :get

end

app/controllers/saml_controller.rb
require "base64"
require "zlib"
require "cgi"
require "net/http"
require "uri"

class SamlController < ApplicationController
  protect_from_forgery :except => [:echo_name_id]

  ASSERTION = "urn:oasis:names:tc:SAML:2.0:assertion"
  PROTOCOL = "urn:oasis:names:tc:SAML:2.0:protocol"

  EVOLUTION_ONE_CLIENTS = %w(advantage assurant)

  PRESET_LOGINS = {
    "Assurant 0003237014" => {
      "account_credential_employer_id" => "AHITST",
      "account_credential_employee_id" => "0032.00101.0000056277.0003237014",
      "account_credential_administrator_alias" => "AHI",
      "account_credential_plan_year_name" => "AHI01012014",
      "account_credential_plan_year_start" => "01/01/2014 00:00:00",
      "account_credential_agent_phone" => "123-456-7890",
      "account_credential_agent_code" => "00013311000001",
      "client" => "assurant",
      "saml_type" => "evo_one",
    },
    "CBCFFMa" => {
      "client" => "cbcffma",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "saml_type" => "cbcffma",
    },
    "CBCFFMr - Off Exchange" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "",
      "account_credential_ffm_partner_consumerid" => "4484",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBCFFMr - Brief Englandpaa" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "94658488",
      "account_credential_ffm_partner_consumerid" => "4485",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBCFFMr - Yellow Lindsaypaa" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "95333946",
      "account_credential_ffm_partner_consumerid" => "4862",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBCFFMr - Great Summerspab" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "94733503",
      "account_credential_ffm_partner_consumerid" => "4796",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBCFFMr - Small Terrellpab" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "94914271",
      "account_credential_ffm_partner_consumerid" => "4807",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBCFFMr - Likely Velezpab" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "95312454",
      "account_credential_ffm_partner_consumerid" => "4822",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBCFFMr - Ezra Humphreypau" => {
      "client" => "cbcffmr",
      "account_credential_employer_id" => "a",
      "account_credential_employee_id" => "b",
      "account_credential_ffm_lastname" => "Wolfe",
      "account_credential_ffm_consumerid" => "95528370",
      "account_credential_ffm_partner_consumerid" => "4797",
      "account_credential_ffm_firstname" => "Steve",
      "account_credential_ffm_partner_token" => "101",
      "account_credential_ffm_usertype" => "Consumer",
      "saml_type" => "cbcffmr",
    },
    "CBC" => {
      "client" => "cbc",
      "account_credential_employer_id" => "CH-DEV",
      "account_credential_employee_id" => "TestEE",
      "saml_type" => "brix",
    },
    "AIC" => {
      "client" => "aic",
      "account_credential_employer_id" => "CH-DEV",
      "account_credential_employee_id" => "TestEE-2",
      "saml_type" => "brix",
    },
    "AIC (ancilliary/life)" => {
      "client" => "aic",
      "account_credential_employer_id" => "AIC_Dev",
      "account_credential_employee_id" => "7961",
      "saml_type" => "brix",
    },
    "AultCare" => {
      "client" => "aultcare-group",
      "account_credential_employer_id" => "CH-DEV",
      "account_credential_employee_id" => "LE-Larry",
      "saml_type" => "brix",
    },
  }

  def new
    @account_credential = AccountCredential.new(params[:account_credential])
    @preset_logins = PRESET_LOGINS
    @client = params[:client]
    @last_environment = session[:last_environment]
    @last_port = session[:last_port] || 80
    @last_protocol = session[:last_protocol]
  end

  def login
    @last_environment = session[:last_environment] = params[:environment]
    @last_port = session[:last_port] = params[:port]
    @last_protocol = session[:last_protocol] = params[:protocol]

    @account_credential = AccountCredential.new(params[:account_credential])
    if params[:client_custom].empty?
      client = params[:client]
    else
      client = params[:client_custom]
    end
    if @account_credential.valid?
      @redirect_url = "#{params[:protocol]}://#{client}.#{params[:environment]}:#{params[:port]}/authentication/saml_authentication/idp_response"
      saml_xml = get_saml_xml(params[:saml_type])
      @saml_response = Base64.encode64(saml_xml)
    else
      render :action => "new"
    end
  end

  def signon
    encoded_saml = params[:SAMLRequest]
    decoded_saml = inflate(Base64.decode64(encoded_saml))

    puts "decoded_saml #{decoded_saml}"

    redirect_url = Nokogiri.XML(decoded_saml).at_xpath('//samlp:AuthnRequest').attribute('AssertionConsumerServiceURL').value
    redirect_url << "?SAMLResponse=#{CGI.escape(Base64.encode64(saml_xml(AccountCredential.instance)))}"
    redirect_to redirect_url

    #raise "#{decoded_saml}"
    #render :text => redirect_url
  end

  def show
    render :text => saml_xml(AccountCredential.instance).html_safe
  end

  def keep_alive
    Rails.logger.info "Keep alive hit - #{Time.now.strftime Time::DATE_FORMATS[:db]}"
    render :text => open(keep_alive_image_path, 'rb').read
  end

  def logout
    Rails.logger.info "Logged out at #{Time.now.strftime Time::DATE_FORMATS[:db]}"

    response = Base64.encode64 File.read("#{Rails.root}/config/slo_successful_response.xml")

    referer_url = URI(request.referer)
    redirect_to "#{referer_url.scheme}://#{referer_url.host}:#{referer_url.port}/authentication/saml_authentication/slo_response?SAMLResponse=#{response}"
  end

  def finish
    Rails.logger.info "Finished at #{Time.now.strftime Time::DATE_FORMATS[:db]}"
    render :text => 'Finish'
  end

  def slo
    enc_saml_response = params[:SAMLRequest]
    decoded_saml_response = Base64.decode64(enc_saml_response)

    if params['Signature'].present?
      pub_key_file = File.read "#{Rails.root}/config/rsa_keys/id_rsa.pub"
      public_key = OpenSSL::PKey::RSA.new(pub_key_file, nil)

      signature = Base64.decode64(params['Signature'])
      encoded_sig_alg = CGI.escape(params['SigAlg'])
      encoded_request = CGI.escape(enc_saml_response)
      url_string = "SAMLRequest=#{encoded_request}&SigAlg=#{encoded_sig_alg}"
      valid_signature = public_key.verify(OpenSSL::Digest::SHA1.new, signature, url_string)

      inflated_saml_response = inflate(decoded_saml_response)
      render :text => "Successful SLO<br/>Valid signature? #{valid_signature}<br/>SAML Request received:<br/>#{ERB::Util.html_escape(inflated_saml_response)}"
    else
      render :text => "Successful SLO<br/>SAML Request received:<br/>#{ERB::Util.html_escape(inflate(decoded_saml_response))}"
    end
  end

  def echo_name_id
    @xml = Nokogiri::XML(Base64.decode64(params['SAMLResponse']))
    @xml.remove_namespaces!
    @name_id = @xml.at_xpath('//Attribute[@Name="ShoppingCartID"]/AttributeValue').try(:text)
    @saml_attributes = @xml.xpath('//Attribute').map {|attr| "#{attr.at_xpath('@Name').try(:value)}: #{attr.at_xpath('AttributeValue').try(:text)}"}
  end

  # Log out
  def request_slo
    @redirect_url = 'http://cbcffmr.ch.localhost:3000/authentication/saml_authentication'
    @saml_response = Base64.encode64(slo_xml)
    render action: 'login'
  end

  private

  def inflate(string)
    zstream = Zlib::Inflate.new(-Zlib::MAX_WBITS)
    buf = zstream.inflate(string)
    zstream.finish
    zstream.close
    buf
  end

  def slo_xml()
    File.read("#{Rails.root}/config/slo.xml")
  end

  def get_saml_xml(saml_type)
    if saml_type == 'evo_one'
      evo_one_saml_xml(@account_credential)
    elsif saml_type == 'cbcffma'
      cbcffma_saml_xml(@account_credential)
    elsif saml_type == 'cbcffmr'
      cbcffmr_saml_xml(@account_credential)
    elsif saml_type == 'brix'
      saml_xml(@account_credential)
    else

app/views/saml/_form.html.erb
<%= form_for(@account_credential, :url => saml_login_path ) do |f| %>
  <% if @account_credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_credential.errors.count, "error") %> prohibited this account_credential from being saved:</h2>

      <ul>
      <% @account_credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :client %><br />
    <%= select_tag :client, options_for_select(
            {
                    'CBC' => 'cbc',
                    'CBC FFM (anonymous)' => 'cbcffma',
                    'CBC FFM (registered)' => 'cbcffmr',
                    'AIC' => 'aic',
                    'Avera Group' => 'avera-group',
                    'AultCare Group' => 'aultcare-group',
                    'Intuit' => 'intuit',
                    'Assurant' => 'assurant',
                    'Paychex' => 'paychex',
                    'Advantage' => 'advantage',
                    '1Plan' => '1plan'
            }, @client || 'cbc') %>
    ...or enter custom client subdomain <small>(if set, takes priority)</small>
    <%= text_field_tag :client_custom %>
  </div>

  <div class="field">
    <%= label_tag :saml_type %><br />
    <%= select_tag :saml_type, options_for_select(
        {
                'BRIX' => 'brix',
                'EvolutionOne' => 'evo_one',
                'CBC FFM (registered)' => 'cbcffmr',
                'CBC FFM (anonymous)' => 'cbcffma',
        }) %>
  </div>

  <div class="field">
    <%= f.label :employer_id %><br />
    <%= f.text_field :employer_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.text_field :employee_id, :style => 'width: 300px' %>
  </div>
  <div class="field">
    <%= f.label :name_id %> (not required)<br />
    <%= f.text_field :name_id %>
  </div>
  <div class="evo1_only">
    <div class="field">
      <%= f.label :administrator_alias %> (only required for Ev1 clients. E.g. Assurant)<br />
      <%= f.text_field :administrator_alias, :value => 'IHD' %>
    </div>
    <div class="field">
      <%= f.label :plan_year_name %> (only required for Ev1 clients. E.g. Assurant)<br />
      <%= f.text_field :plan_year_name %>
    </div>
    <div class="field">
      <%= f.label :plan_year_start %> (only required for Ev1 clients. E.g. Assurant)<br />
      <%= f.text_field :plan_year_start, :placeholder => 'MM/DD/YYYY HH:MM:SS' %>
    </div>
    <div class="field">
      <%= f.label :agent_phone %> (only required for Ev1 clients. E.g. Assurant)<br />
      <%= f.text_field :agent_phone %>
    </div>
    <div class="field">
      <%= f.label :agent_code %> (only required for Ev1 clients. E.g. Assurant)<br />
      <%= f.text_field :agent_code %>
    </div>
    <div class="field">
      <%= f.label :agent_name %> (only required for Ev1 clients. E.g. Assurant)<br />
      <%= f.text_field :agent_name %>
    </div>
  </div>
  <div class="ffm_only">
    <div class="field">
      <%= f.label :uuid %> (only used for CBCFFMr)<br />
      <%= f.text_field :uuid, :placeholder => 'XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' %>
    </div>
    <div class="field">
      <%= f.label "First name (FFM)" %><br />
      <%= f.text_field :ffm_firstname %>
    </div>
    <div class="field">
      <%= f.label "Last name (FFM)" %><br />
      <%= f.text_field :ffm_lastname %>
    </div>
    <div class="field">
      <%= f.label "FFM Consumer ID (FFM)" %><br />
      <%= f.text_field :ffm_consumerid %>
    </div>
    <div class="field">
      <%= f.label "Partner consumer ID (FFM)" %><br />
      <%= f.text_field :ffm_partner_consumerid %>
    </div>
    <div class="field">
      <%= f.label "Partner logging token (FFM)" %><br />
      <%= f.text_field :ffm_partner_token %>
    </div>
    <div class="field">
      <%= f.label "User Type (FFM)" %><br />
      <%= f.text_field :ffm_usertype %>
    </div>
    <div class="field">
      <%= f.label "Issuer Shopping Cart ID (FFM)" %><br />
      <%= f.text_field :ffm_issuer_shopping_cart_id %>
    </div>
  </div>
  <div class="field">
    <%= label_tag :environment %><br />
    <%= select_tag :environment, options_for_select({"Staging" => "stg.connectedhealth.com",
                                                     "Merge" => "merge.connectedhealth.com",
                                                     "TBox Merge" => "tb-merge.connectedhealth.com",
                                                     "TBox Staging" => "tb-stg.connectedhealth.com",
                                                     "Localhost" => 'ch.localhost' }, @last_environment) %>
  </div>
  <div class="field">
    <%= label_tag :protocol %><br />
    <%= select_tag :protocol, options_for_select({ "http" => "http", "https" => "https" }, @last_protocol) %>
  </div>
  <div class="field">
    <%= label_tag :port %><br />
    <%= text_field_tag :port, @last_port %>
  </div>

  <div class="actions">
    <%= f.submit "Login" %>
  </div>

  <div>
    <p>See <a href="https://github.com/connectedhealth/Health-Care-Cost-Calculator/wiki/Clients-users-and-credentials">Users and Credentials</a></p>
  </div>
<% end %>

<script>
    $(function() {
        $('.ffm_only').hide();
        $('.evo1_only').hide();

        $('#client').change(function() {
            var selectedClient = $('#client option:selected').val();

            if (selectedClient == 'cbcffmr') {
              $('.ffm_only').show();
            } else {
              $('.ffm_only').hide();
            }

            if (selectedClient == 'assurant' || selectedClient == 'advantage') {
                $('.evo1_only').show();
            } else {
                $('.evo1_only').hide();
            }
        });
    });
</script>

app/views/saml/echo_name_id.html.erb
<% if @name_id.blank? %>
  No name id present!
<% else %>
  Login with the following uuid <a href='<%="#{saml_new_path}?client=cbcffmr&account_credential[uuid]=#{@name_id}&account_credential[employee_id]=a&account_credential[employer_id]=b"%>'>here</a>: <%=@name_id%>
<% end %>
<br />
SAML attributes received:
<%= @saml_attributes.join('<br />').html_safe %>

app/views/saml/login.html.erb
<%= form_tag(@redirect_url) do %>
  <%= hidden_field_tag :SAMLResponse, @saml_response %>
<% end %>
<script type='text/javascript'> window.onload = function(){ window.document.forms[0].submit(); }; </script>

app/views/saml/new.html.erb
<%= link_to "Secure Log Out for CBCFFMr (localhost only)", saml_request_slo_path %>

<h1>Single Sign On</h1>

<ul id="presets">
  <% @preset_logins.try(:each) do |login, fields| %>
    <li>
      <a href="#" onclick="loadPreset('<%= login %>'); return false;"><%= login %></a>
    </li>
  <% end %>
</ul>

<%= render 'form' %>

<%= javascript_tag do %>
window.preset_logins = <%= raw @preset_logins.to_json %>;

window.loadPreset = function(presetName) {
  $("input[type='text']:not([name='port']), select:not([name='environment']):not([name='protocol'])").val("");
  _(window.preset_logins[presetName]).chain().
    pairs().
    each(function(field) {
      var id = field[0];
      var value = field[1];
      $("#"+id).val(value).change();
    });
}
<% end %>

<%= javascript_include_tag 'login.js' %>